name: business-management-backend
services:
  - name: api
    github:
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_EXPIRATION
        value: 1d
      - key: PORT
        value: "3000"
      - key: FRONTEND_URL
        value: https://your-frontend-url.com
