trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: business-management-variables

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - task: Docker@2
    inputs:
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: 'business-management-backend'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.BuildId)'

  - task: AzureWebAppContainer@1
    inputs:
      azureSubscription: '$(azureSubscription)'
      appName: '$(webAppName)'
      containers: '$(containerRegistry)/business-management-backend:$(Build.BuildId)'
      appSettings: |
        [
          {
            "name": "WEBSITES_PORT",
            "value": "3000",
            "slotSetting": false
          }
        ]
