services:
  - type: web
    name: business-management-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 1d
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: https://your-frontend-url.com
    healthCheckPath: /health
    autoDeploy: true
